version: "3.7"
services:
  jamulus1:
    container_name: jamulus1
    image: grundic/jamulus
    restart: always
    volumes:
      - ./room1:/rec
    ports:
      - "22124:22124/udp"
    entrypoint:
      - "Jamulus"
      - "--server"
      - "--nogui"
      - "--welcomemessage"
      - "MIT VGO ^-^: Room 1 🔥"
      - "--numchannels"
      - "16"
      - "--recording"
      - "/rec"
      - "--norecord"
  jamulus2:
    container_name: jamulus2
    image: grundic/jamulus
    restart: always
    volumes:
      - ./room2:/rec
    ports:
      - "22125:22124/udp"
    entrypoint:
      - "Jamulus"
      - "--server"
      - "--nogui"
      - "--welcomemessage"
      - "MIT VGO ^-^: Room 2 💧"
      - "--numchannels"
      - "16"
      - "--recording"
      - "/rec"
      - "--norecord"
  jamulus3:
    container_name: jamulus3
    image: grundic/jamulus
    restart: always
    volumes:
      - ./room3:/rec
    ports:
      - "22126:22124/udp"
    entrypoint:
      - "Jamulus"
      - "--server"
      - "--nogui"
      - "--welcomemessage"
      - "MIT VGO ^-^: Room 3 🍃"
      - "--numchannels"
      - "16"
      - "--recording"
      - "/rec"
      - "--norecord"
