version: "3.7"
services:
  jamulus1:
    container_name: jamulus1
    image: grundic/jamulus
    restart: always
    ports:
      - "22124:22124/udp"
    entrypoint:
      - "Jamulus"
      - "--server"
      - "--nogui"
      - "--welcomemessage"
      - "MIT VGO ^-^"
      - "--numchannels"
      - "16"
      - "--recording"
      - "./recordings/channel1"
      - "--servername"
      - "MIT VGO ROOM 1"
  jamulus2:
    container_name: jamulus2
    image: grundic/jamulus
    restart: always
    ports:
      - "22125:22124/udp"
    entrypoint:
      - "Jamulus"
      - "--server"
      - "--nogui"
      - "--welcomemessage"
      - "MIT VGO ^-^"
      - "--numchannels"
      - "16"
      - "--recording"
      - "./recordings/room2"
      - "--servername"
      - "MIT VGO ROOM 2"
  jamulus3:
    container_name: jamulus3
    image: grundic/jamulus
    restart: always
    ports:
      - "22126:22124/udp"
    entrypoint:
      - "Jamulus"
      - "--server"
      - "--nogui"
      - "--welcomemessage"
      - "MIT VGO ^-^"
      - "--numchannels"
      - "16"
      - "--recording"
      - "./recordings/room3"
      - "--servername"
      - "MIT VGO ROOM 3"
